#!/bin/ksh
#
# Sample 10g CRS resource status query script
#
# Description:
#    - Returns formatted version of crs_stat -t, in tabular
#      format, with the complete rsc names and filtering keywords
#   - The argument, $RSC_KEY, is optional and if passed to the script, will
#     limit the output to HA resources whose names match $RSC_KEY.
# Requirements:
#   - $GRID_HOME should be set in your environment 

RSC_KEY=$1
AWK=/bin/awk    # if not available use /usr/bin/awk

# Table header:echo ""
$AWK \
  'BEGIN {printf "%-35s %-10s %-18s\n", "HA Resource", "Target", "State";
          printf "%-35s %-10s %-18s\n", "-----------", "------", "-----";}'

# Table body:
$CRS_HOME/bin/crsctl stat resource -v | $AWK \
 'BEGIN { FS="="; state = 0; }
  $1~/NAME/ {appname = $2; state=1};
  $1~/LAST_SERVER/ {state=1};
  state == 0 {next;}
  $1~/TARGET/ && state == 2 {apptarget = $2; state=3;}
  $1~/STATE/ && state == 1 {appstate = $2; state=2;}
  $1~/STATE_DETAILS/ && state == 3 && $2~/.+/ {appstate=appstate " - "$2; state=4;}
  $1~/STATE_DETAILS/ && state == 3 && ! $2~/.+/ {state=4;}
  state == 4 && appname~/'$RSC_KEY'/ {printf "%-35s %-10s %-18s\n", appname, apptarget, appstate; state=0;}'
